EXP_NAME: "UNet_CILonly"
LOGDIR: 'logs/'
DATASET:
  BATCHSIZE: 32
  TRAIN_DS: 'cil'
  VAL_DS: 'cil'
  TEST_DS: 'cil'
  PATCH_SIZE: 208
  PATCH_STRIDE: 96
  CIL:
    PATH: 'data/cil'     
  USE_AUG: True
  
  AUG:
    ROTATE_PROB: 0.75
    FLIP_PROB: 0.5
    RANDOM_BRIGHTNESSCONTRAST_PROB: 0.75

OPTIMIZER:
  LR: 0.0001

TRAINING:
  LOG_FREQ_IMAGES: 30 
  LOG_IMAGES: True
  EPOCHS: 200