EXP_NAME: "UNet_CIL_dice_ptMSRoads_mmp0"
LOGDIR: '/cluster/scratch/jminder/RoadSegmentation/'
DATASET:
  BATCHSIZE: 32
  TRAIN_DS: 'cil'
  VAL_DS: 'cil'
  TEST_DS: 'cil'
  PATCH_SIZE: 208
  PATCH_STRIDE: 96
  CIL:
    PATH: '/cluster/scratch/jminder/RoadSegmentation/data/cil'     
  USE_AUG: True
  MIN_MASK_PERCENTAGE: 0.0

  AUG:
    ROTATE_PROB: 0.75
    FLIP_PROB: 0.5
    RANDOM_BRIGHTNESSCONTRAST_PROB: 0.75

OPTIMIZER:
  LR: 0.0001

TRAINING:
  LOG_IMAGES: True
  EPOCHS: 200
  PRETRAINED_MODEL: '/cluster/scratch/jminder/RoadSegmentation/CIL-RoadSegmentation/68boo5nh/checkpoints/epoch=15-step=55596.ckpt'
LOSS:
  NAME: "DiceLoss"

TEST:
  SUBMISSION_PATH: "pt_msroads_dice_mmp0_submission.csv"
