EXP_NAME: "UPerNet"
LOGDIR: 'logs'
DATASET:
  BATCHSIZE: 32
  TRAIN_DS: 'cil'
  VAL_DS: 'cil'
  TEST_DS: 'cil'
  PATCH_SIZE: 208
  PATCH_STRIDE: 96
  CIL:
    PATH: 'data/cil'     
  USE_AUG: False 
  
  AUG:
    ROTATE_PROB: 0.75
    FLIP_PROB: 0.5
    RANDOM_BRIGHTNESSCONTRAST_PROB: 0.75

OPTIMIZER:
  LR: 0.0001

TRAINING:
  LOG_IMAGES: True
  EPOCHS: 200

LOSS:
  NAME: "BCEDiceLoss"

TEST:
  SUBMISSION_PATH: "pt_airs_ttat_submission.csv"
  USE_TTA: True
  TTA_STRATEGY: "thres"
  POSTPROCESSING:
    USE_MEDIAN_BLUR: False
    USE_LOW_NOISE_REMOVAL: False
    USE_GAUS_THRES: False
    USE_BLOB_REMOVAL: False
  
MODEL:
  ARCH: "UperNet"
  